# Test
FROM node:20 AS test-stage

WORKDIR /usr/src/app
COPY . .
RUN npm ci
RUN npm run test

# Build
FROM node:20 AS build-stage

WORKDIR /usr/src/app
COPY . .

ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

RUN npm ci
RUN npm run build

# Run
FROM nginx:1.25-alpine

COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html
