services:
  server:
    container_name: server
    build:
      context: ./phonebook-backend
      dockerfile: dev.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./phonebook-backend:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database?authSource=the_database
      - PORT=3001
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "3456:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./phonebook-backend/models/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./phonebook-backend/mongo_data:/data/db

  app:
    container_name: app
    build:
      context: ./phonebook-frontend
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./phonebook-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
      - server
